### ISSUE TITLE
《接下来我会骂三个游戏》

### ISSUE THREAD

**Issue by NWYLZW** [NoneMeme/NoneMeme#26]
<img width="460" alt="image" src="https://user-images.githubusercontent.com/51358815/189839849-268d7f65-56c7-4080-a213-0774d508c238.png">

<img width="460" alt="image" src="https://user-images.githubusercontent.com/51358815/189841454-d6f434ad-be0e-4dc5-9d10-ac9bfe4d6523.png">

**Comment by Geno1024** [comment]
建议打码以免误伤

**Comment by Nranphy** [comment]
> 建议打码以免误伤

不打码、我在图里加批注就好了，都自己人///v///

**Comment by Nranphy** [comment]
已上传
