### ISSUE TITLE
从CICD自动构建迁移到Github API以及此结构对不同运行环境的适配性

### ISSUE THREAD

**Issue by Seidko** [NoneMeme/NoneMeme#27]
目前我要做的是完全重构整个项目。现在的图片列表加载有一个问题，是静态的，每次commit都要 靠CI来重新生成这个列表，这无疑是不优雅的，所以我想到了动态获取图片列表，这就遇到了一个问题，怎么获取到图片列表?然后查找资料以及阅读文档以后，查询到了Github有这方面的API：

```javascript
`https://api.github.com/repos/{$userName}/{$repoName}/contents/{$path}/?ref={$branch}`
```

但是如何区分是在本项目，还是fork项目，抑或是clone下来自己建服务器怎么办呢?都是调GitHub查询本项目的文件列表?如果别人想用自己的图片库呢?

所以现在就需要讨论这个内容怎么实现了。

**Comment by NWYLZW** [comment]
需求背景没有很好的解释

## 迁移至使用 github api 作为图片数据获取源

### 需求背景

目前使用的是 CICD 进行的数据生成，但是 github 提供了对应的 api ，可以获取到指定目录的文件列表。

故使用相关 API 进行改造

### 可能的问题

* 无法判断开发者的环境，去加载数据
* fork 之后没办法在 fork 出来的项目看到对应的文件
  假设我是 foo，fork 了一个项目，那么我访问项目就是 foo.github.io/nonememe
  但是实际上并没有考虑这个问题，需要对该情况做兼容
* ...其他可能的问题

按照我说的改改吧

**Comment by NWYLZW** [comment]
如何处理在本地开发的图片加载问题？

**Comment by NWYLZW** [comment]
如何处理 fork 后拉取的还是 nonememe 的图源？
例如用户 foo fork 了本项目，实际上它需要的图源是在 foo.github.io/nonememe

**Comment by Seidko** [comment]
> 如何处理在本地开发的图片加载问题？

动态获取列表的话就不能使用file协议，cors policy不允许xhr获取file列表，如果有人clone下来直接打开index.html就不好办了

所以还是要恢复静态吗😭

**Comment by Seidko** [comment]
目前我的想法是暂时不处理 file protocol，或者是保留`config`，当检测到protocol为`file`时启用`config`

**Comment by NWYLZW** [comment]
> > 如何处理在本地开发的图片加载问题？
> 
> 动态获取列表的话就不能使用file协议，cors policy不允许xhr获取file列表，如果有人clone下来直接打开index.html就不好办了
> 
> 所以还是要恢复静态吗😭

* plan 0: 使用 webpack 进行支持
* plan 1: 使用俩个方案，本地开发的时候使用静态文件，线上使用 gtihub api
  这个方案需要统一一个共用的 api

**Comment by NWYLZW** [comment]
> 目前我的想法是暂时不处理 file protocol，或者是保留`config`，当检测到protocol为`file`时启用`config`

fileprotocol 倒是不用怎么考虑了，开发者还是需要使用一个 live server 类似的进行项目开发
单纯 clone 下来然后用 file protocol 打开还是比较少的一个需求

**Comment by Seidko** [comment]
我打算在开发环境中使用vscode的live server插件并对其做适配，静态就暂时先不考虑了

**Comment by Seidko** [comment]
而且我思考了一下，fork之后的项目的存储库名字，用户名都不能确定，导致想要获取API的URL都很难确定，如果在代码里判断应该是很难做到的，所以还不如让fork了项目的人自行改动API，这应该是比较好的解决办法

如果不想这么做，就只能继续静态了

**Comment by NWYLZW** [comment]
> 而且我思考了一下，fork之后的项目的存储库名字，用户名都不能确定，导致想要获取API的URL都很难确定，如果在代码里判断应该是很难做到的，所以还不如让fork了项目的人自行改动API，这应该是比较好的解决办法
> 
> 如果不想这么做，就只能继续静态了

先看看这个，你觉得哪个做比较好
https://github.com/NoneMeme/NoneMeme/issues/27#issuecomment-1261718013

类似这种项目本来就是 fork 维护的，如果 fork 的支持很差的话对项目发展是不太好的

**Comment by NWYLZW** [comment]
> 我目前写了一套这样的代码：
> 
> ```js
> // 开发环境(使用live server)
> if (development) {
>     const xhr = new XMLHttpRequest()
>     xhr.open('GET', './meme/')
>     xhr.addEventListener('load', () => {
>         for (let i of domParser.parseFromString(xhr.response, 'text/html').querySelectorAll('#files a.icon-image')) {
>             item.push(decodeURIComponent(i.href.match(/(?<=meme\/).+\.(jpg|png|jfif|webp|gif)/)[0]))
>         }
>     })
>     xhr.send()
>     
> // 生产环境
> } else {
>     const xhr = new XMLHttpRequest()
>     xhr.open('GET', 'https://api.github.com/repos/NoneMeme/NoneMeme/contents/meme')
>     xhr.addEventListener('load', () => {
>         for (let i of JSON.parse(xhr.response)) {
>             item.push(decodeURIComponent(i.download_url.match(/(?<=meme\/).+\.(jpg|png|jfif|webp|gif)/)[0]))
>         }
>     })
>     xhr.send()
> }
> ```
> 
> 本地用live server的文件服务做适配，GitHub上调用API，看看这样可不可以？

考虑一下从 location 里面拿这个值
<img width="745" alt="image" src="https://user-images.githubusercontent.com/51358815/193028664-e51d5d98-38be-4f82-81ee-9d8ffe90efcd.png">

* development 咋判断的，你发个 pr 我看看

**Comment by Seidko** [comment]
> development 咋判断的，你发个 pr 我看看

还是localhost check
```js
const development = location.host.search('127.0.0.1') != -1 || location.host.search('localhost') != -1
```

**Comment by NWYLZW** [comment]
> > development 咋判断的，你发个 pr 我看看
> 
> 还是localhost check
> 
> ```js
> const development = location.host.search('127.0.0.1') != -1 || location.host.search('localhost') != -1
> ```

我觉得你这个判断有问题，按道理来说判断不是生产环境的成本更小

**Comment by Seidko** [comment]
> 我觉得你这个判断有问题，按道理来说判断不是生产环境的成本更小

改成判断 location.host 有没有 *.github.io ？
