### ISSUE TITLE
使用 github api 的新版本很容易触发限制导致没办法加载图片

### ISSUE THREAD

**Issue by NWYLZW** [NoneMeme/NoneMeme#31]
如题
<img width="1312" alt="image" src="https://user-images.githubusercontent.com/51358815/194793640-15b76ec2-7e51-4057-be7c-7e07749f06cc.png">
<img width="1353" alt="5b7f808fd6e4ee694f3e85a634799b0c" src="https://user-images.githubusercontent.com/51358815/194793648-d19ae4c2-b708-4ef7-a84c-e3b3d736821e.png">

**Comment by NWYLZW** [comment]
我认为文件信息在每次更新的时候都是确定的，其实不应该使用动态的 api 进行请求

**Comment by NWYLZW** [comment]
> 确实应该这么干……因为网站图片绝大部分内容是静态的，如果使用动态内容反而会有负面效果
> 
> 不过本地开发还是用新API吧，毕竟本地也没有什么API rate limit，动态的也更利于开发

话说你本地不是直接用的本地的数据吗？我记得你说用的啥 liveserver 的 api

**Comment by Seidko** [comment]
> 话说你本地不是直接用的本地的数据吗？我记得你说用的啥 liveserver 的 api

是的，所以我没有改本地的API，只在生产环境使用静态文件

**Comment by NWYLZW** [comment]
> 是的，所以我没有改本地的API，只在生产环境使用静态文件

ok，晚点我看看
